### ISSUE TITLE
Scroll event isn't unregistered correctly

### ISSUE THREAD

**Issue by jkjustjoshing** [hexagoncircle/scrollspy-nav#1]
Just read your blog post from a week ago and was peeking through the code. I noticed you have your [`handleScroll()` method](https://github.com/hexagoncircle/scrollspy-nav/blob/main/scrollspy-nav.js#L121) that sets a scroll listener, and then unregisters the event handles at a specific moment.

There is a bug for browsers that don't support the `scrollend` event - the event handler function that's registered on the `scroll` event on [line 137](https://github.com/hexagoncircle/scrollspy-nav/blob/0e798548ca3609afb683442d7e953f020a60674c/scrollspy-nav.js#L137) isn't the function one that gets unregistered on [line 130](https://github.com/hexagoncircle/scrollspy-nav/blob/0e798548ca3609afb683442d7e953f020a60674c/scrollspy-nav.js#L130), so the event is never actually removed.

Thought you might want to know!

**Comment by hexagoncircle** [comment]
Ah yes—good catch, @jkjustjoshing! Pushed up a fix 👍
